### ISSUE TITLE
Error compiling kernel

### ISSUE THREAD

**Issue by chiteroman** [wxt1221/KernelSU#1]
ld.lld: error: undefined symbol: may_mount
>>> referenced by core_hook.c:47 (/root/kernel_xiaomi_vayu/out/../drivers/kernelsu/core_hook.c:47)
>>>               drivers/kernelsu/core_hook.o:(try_umount) in archive built-in.o
>>> did you mean: may_umount
>>> defined in: built-in.o(fs/namespace.o)

ld.lld: error: undefined symbol: check_mnt
>>> referenced by core_hook.c:51 (/root/kernel_xiaomi_vayu/out/../drivers/kernelsu/core_hook.c:51)
>>>               drivers/kernelsu/core_hook.o:(try_umount) in archive built-in.o

ld.lld: error: undefined symbol: do_umount
>>> referenced by core_hook.c:65 (/root/kernel_xiaomi_vayu/out/../drivers/kernelsu/core_hook.c:65)
>>>               drivers/kernelsu/core_hook.o:(try_umount) in archive built-in.o

ld.lld: error: undefined symbol: mntput_no_expire
>>> referenced by core_hook.c:69 (/root/kernel_xiaomi_vayu/out/../drivers/kernelsu/core_hook.c:69)
>>>               drivers/kernelsu/core_hook.o:(try_umount) in archive built-in.o

**Comment by chiteroman** [comment]
Forgot to patch namespace.c XD

**Comment by SonalSingh18** [comment]
> Forgot to patch namespace.c XD

I am having this same error, from your reply it seems you have it fixed
