### ISSUE TITLE
从0.7.5版本到0.7.6版本升级后显示未安装

### ISSUE THREAD

**Issue by WYXHY-Cimolestes** [wxt1221/KernelSU#10]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

先是用kernelflash刷了一遍，但无效，在用电脑刷了一遍还是没用，换了原来的0.7.5的管理器也不行（内核是0.7.6发布资源里的）
实际上，除了UI显示未安装以外，其他功能还有lsp模块都还在，正常的root原先授权的也都在（不不不，刚试了，都失效了）

### Screenshots

![Screenshot_2024-01-11-12-39-10-92_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/wxt1221/KernelSU/assets/47136792/9695bbc5-d3b1-4efb-847c-f056c5172a4c)

### Device info

- Device:一加ACE2pro
- OS Version:14
- KernelSU Version:0.7.6

**Comment by WYXHY-Cimolestes** [comment]
日志：
[Uploading KernelSU_bugreport_2024-01-11_12_40.tar.gz…]()

**Comment by WYXHY-Cimolestes** [comment]
哇，大佬救命啊，现在我回退到之前的版本了0.7.5，可能是我这个手机，因为听说coloros14在这个手机上不能乱刷内核，哎呀，现在我都不敢升级ksu了😭还有原来weishu大佬编译的kernelflash alpha-13版本还能用吗？，为什么我两三次升级这个内核都用不了，我都是只能用电脑了

**Comment by WYXHY-Cimolestes** [comment]
以后再也不乱升级了，差点我都打算9008了，这手机color系统，一言难尽，还是习惯小米

**Comment by wxt1221** [comment]
貌似是签名坏了，不过我应该是修过的，我再看看哈

**Comment by wxt1221** [comment]
不要用原来的管理器，签名不一致

**Comment by WYXHY-Cimolestes** [comment]
> 貌似是管理器的签名坏了，不过我应该是修过的，我再看看哈。
> 
> 现在是只有管理器不显示，su、模块实际上都在吗？

没有，我来来回回刷过好几次，新的内核，第一遍的话，重启以后都在第二遍，也还在第三遍的时候root没有了，第456遍lsp仍然都在，我感觉这个应该是我手机的问题😅低人二等的加人是这样的🤣，因为社区有人说我这个手机C14不能乱刷内核，要更换内核的话得清空data再刷，我寻思着ksu升级内核好像也算是刷了个新内核了吧，不清楚，反正这手机是这样的，我也搞不懂

**Comment by wxt1221** [comment]
我知道了，签名的大小没更新，疏忽了（，稍等一下我修一下

**Comment by WYXHY-Cimolestes** [comment]
> 不要用原来的管理器，签名不一致

就是说这个管理器得先卸载，原来的再安装这个新版本的，然后再刷内核吗？我原来的步骤是直接忽略了签名验证覆盖安装了，然后再去刷内核的是这个校验的问题，导致ksu把内核锁了？

**Comment by wxt1221** [comment]
是我的问题，签名没改好

**Comment by WYXHY-Cimolestes** [comment]
> 我知道了，签名的大小没更新，疏忽了（，稍等一下我修一下

？？？我回答的这么模糊都知道？我看了下日志上也没写什么东西呀wc，大佬

**Comment by wxt1221** [comment]
我推了一个commit,构建好后，安装这个里面的内核就行了

**Comment by WYXHY-Cimolestes** [comment]
> 是我的问题，签名没改好

你现在如果我要升级的话，我应该怎么做？先写在原来的管理器，再安装新的管理器，再刷内核吗？能不能不卸载原来的管理器，就是直接覆盖安装？已经核心破解了

**Comment by WYXHY-Cimolestes** [comment]
> 我推了一个commit,构建好后，安装这个里面的内核就行了

好的好的，明白了
