### ISSUE TITLE
KernelSU Manager showing not installed when I have installed the Anykernel zip through recovery for my Device Pixel 6

### ISSUE THREAD

**Issue by xxxsskxxx** [wxt1221/KernelSU#13]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

As the previous repo is now read only.

I have migrated to this repo.
I used AnyKernel3-android13-5.10.157_2023-03.zip and pushed via adb / recovery to my Pixel 6, all went well.

I installed the 0.7.6 KSU manager, and it states its not installed.
![Screenshot_20240111-160636_KernelSU](https://github.com/wxt1221/KernelSU/assets/96975040/85b07418-3f1c-4627-a499-f60a69fcb739)
[KernelSU_bugreport_2024-01-11_16_04.tar.gz](https://github.com/wxt1221/KernelSU/files/13905666/KernelSU_bugreport_2024-01-11_16_04.tar.gz)

Screenshot and manager bug report attached.

### To Reproduce

1. Open app
2.  KSU 0.7.6 advises not installed

### Device info

- Device: Pixel 6 [oriole]
- OS Version: LineageOS 20 (A13)
- KernelSU Version: 0.7.6
- Kernel Version: 5.10.157

**Comment by holyangel** [comment]
Yeah I'm seeing the same thing here with shusky using the 7.6 tag and the new(or even old) manager app. I haven't tried building kernelsu at 'main' yet but.. something is up 🤔

**Comment by y0geshx** [comment]
Cuz KernelSU Manager application signatures changed 🥲, so it's showing unsupported or not installed.

**Comment by wxt1221** [comment]
Just use the newest manager

**Comment by meiser79** [comment]
I'm running app version 0.7.6-15-gf79388. Installing this app did not upgrade the ksud binary to latest version, it was still 0.7.5. I had to manually download it from CI (it's version 0.7.6-9-gb85090e).

But the Manager app hangs at startup, I only see the logo, that's it.

**Comment by xxxsskxxx** [comment]
Sorry is this the latest GitHub action build? 

What CI Manager? Can't see that in the release area.

Where do I get this from?

**Comment by wxt1221** [comment]
> Sorry is this the latest GitHub action build?
> 
> What CI Manager? Can't see that in the release area.
> 
> Where do I get this from?

Yes

**Comment by wxt1221** [comment]
> I'm running app version 0.7.6-15-gf79388. Installing this app did not upgrade the ksud binary to latest version, it was still 0.7.5. I had to manually download it from CI (it's version 0.7.6-9-gb85090e).
> 
> But the Manager app hangs at startup, I only see the logo, that's it.

Try to restart the manager.

**Comment by meiser79** [comment]
> Try to restart the manager.

Already force closed the app. No change in behaviour.

**Comment by wxt1221** [comment]
> > Try to restart the manager.
> 
> Already force closed the app. No change in behaviour.

I do not think that's ksu's bug. The same thing happens with my phone sometimes. Open it later. Or try to reinstall

**Comment by meiser79** [comment]
logcat is flodded with these messages while I see the logo:
```
01-12 09:50:16.741  1748  1796 W ActivityManager: ProcessRecord{54b7e9f 0:me.weishu.kernelsu/u0a561} is attached to a previous process 26316
01-12 09:50:16.820  1748  1804 E ActivityManager: ProcessRecord{54b7e9f 0:me.weishu.kernelsu/u0a561} 26316 refused to die while trying to launch ProcessRecord{38b5fe1 0:me.weishu.kernelsu/u0a561}, cancelling the process start
```

Reinstalling the app does not change the behaviour. It's quite strange that this does not happen at all with tiann's version 0.7.5. So there must be something wrong.

**Comment by wxt1221** [comment]
Nothing changed but signature

**Comment by marshmello61** [comment]
> I'm running app version 0.7.6-15-gf79388. Installing this app did not upgrade the ksud binary to latest version, it was still 0.7.5. I had to manually download it from CI (it's version 0.7.6-9-gb85090e).
> 
> But the Manager app hangs at startup, I only see the logo, that's it.

I can confirm the issue
