### ISSUE TITLE
Latest manager app just hanging up at startup

### ISSUE THREAD

**Issue by marshmello61** [wxt1221/KernelSU#15]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

As mentioned in the earlier issue https://github.com/wxt1221/KernelSU/issues/13#issuecomment-1888645347 created, quoting below

> I'm running app version 0.7.6-15-gf79388. Installing this app did not upgrade the ksud binary to latest version, it was still 0.7.5. I had to manually download it from CI (it's version 0.7.6-9-gb85090e).
> 
> But the Manager app hangs at startup, I only see the logo, that's it.

Meaning the latest manager app just hanging up at startup. Not even opening the app.

### To Reproduce

1. Open app
2. Wait for it to open
3. Notice that it got hanged

### Expected behavior

Should open

### Device info

- Device: realme 7 pro
- OS Version: 14
- KernelSU Version: 0.7.6
- Kernel Version: 4.14.y

**Comment by Grill-Laux** [comment]
Similar Question...

**Comment by wxt1221** [comment]
Is the manager from release work properly?

**Comment by Grill-Laux** [comment]
> properly

No

**Comment by wxt1221** [comment]
https://github.com/wxt1221/KernelSU/actions/runs/7473769216/job/20338653386

Will this manager open?

**Comment by Grill-Laux** [comment]
> https://github.com/wxt1221/KernelSU/actions/runs/7473769216/job/20338653386
> 
> Will this manager open?

Exactly didn't

**Comment by wxt1221** [comment]
Try the newest CI

**Comment by wxt1221** [comment]
The problem doesn't seem solve out.

**Comment by marshmello61** [comment]
> https://github.com/wxt1221/KernelSU/actions/runs/7473769216/job/20338653386
> 
> Will this manager open?

The manager app in this workflow opens fine. But seems mismatch for apk hash as it doesn't detect ksu.

**Comment by marshmello61** [comment]
Installed the app in latest ci. App opens but doesn't detect ksu?

**Comment by wxt1221** [comment]
> Installed the app in latest ci. App opens but doesn't detect ksu?

That's OK. I update signature. Then I will update the signature in kernel. Please wait for a moment.

**Comment by wxt1221** [comment]
Could you give me the signature？

**Comment by wxt1221** [comment]
Recomplie the kernel

**Comment by marshmello61** [comment]
> Recomplie the kernel

Recompiled kernel with new hash and size. But now the issue started again. App hangs on the start up.

**Comment by wxt1221** [comment]
I'm really confused now.

**Comment by wxt1221** [comment]
Could you offer logcat and dmesg to me?

**Comment by marshmello61** [comment]
> Could you offer logcat and dmesg to me? @marshmello61 @Grill-Laux
> 
> I don't have any devices to test it.

User meiser79 mentioned in https://github.com/wxt1221/KernelSU/issues/13#issuecomment-1888691631 that the log was flooded with 
```
01-12 09:50:16.741  1748  1796 W ActivityManager: ProcessRecord{54b7e9f 0:me.weishu.kernelsu/u0a561} is attached to a previous process 26316
01-12 09:50:16.820  1748  1804 E ActivityManager: ProcessRecord{54b7e9f 0:me.weishu.kernelsu/u0a561} 26316 refused to die while trying to launch ProcessRecord{38b5fe1 0:me.weishu.kernelsu/u0a561}, cancelling the process start
```

If you want more log, I'll try to grab once I get home

**Comment by wxt1221** [comment]
dmesg in the same time please

**Comment by wxt1221** [comment]
The problem was solved with the newest source.

**Comment by marshmello61** [comment]
After commit bce36a3c1273b3c8e3930b8dc3738b8bb179d123, I recompiled kernel and seems latest ci manager app opens fine and shows ksu installed. Thanks for the help.

**Comment by wxt1221** [comment]
That's caused by the size of signature is not right. A Genshin problem.

**Comment by marshmello61** [comment]
I see. I didn't knew signature size can cause that much of issue. Learnt a new thing
