### ISSUE TITLE
手机系统更新后管理器无法识别root权限

### ISSUE THREAD

**Issue by wuj2526** [wxt1221/KernelSU#16]
手机系统更新时，用kernel flasher刷入另一个卡槽后重启，模块还在，lsp也能够使用，但是所有授权root的软件root权限全部丢失，并且KSU管理器识别不了root，无论是0.7.5版本还是0.7.6版本。手机为真我GTNeo3，系统版本为RealmeUI5.0，安卓14。内核为Android12-5.10.168

**Comment by wxt1221** [comment]
0.7.5是weishi那个吗

**Comment by wxt1221** [comment]
提供日志

**Comment by wuj2526** [comment]
> 0.7.5是weishi那个吗

是的。我现在无法查看日志，没办法给mt授权。我本来想用shizuku进行授权，用无线调试功能一直显示正在匹配，然后失败，电脑用adb命令激活显示permission denied权限被拒绝

**Comment by wxt1221** [comment]
用adb

**Comment by wuj2526** [comment]
> 用adb

- ![KernelSU_bugreport_2024-01-13_19_34.tar.gz](https://github.com/wxt1221/KernelSU/files/13927944/KernelSU_bugreport_2024-01-13_19_34.tar.gz)

这是ksu里面的发送日志功能带的日志。我用激活shizuku给mt授权，在data文件夹内没有ksu😭，所以我只能发APP内部的发送日志

**Comment by wxt1221** [comment]
![image](https://github.com/wxt1221/KernelSU/assets/74451279/64dcfb41-36b8-4b44-9f1a-de37aacc5d98)
不是啊，你这个日志如给啊

**Comment by wxt1221** [comment]
在adb shell里面运行
```bash
dmesg>/sdcard/dmesg
logcat>/sdcard/logcat
```

把这两个文件发上来

**Comment by ItosEO** [comment]
一般要logcat -d > /sdcard/logcat
至少vivo是的，为了防止logcat造成阻塞

. Logcat调用限制
APP若在运行时需要读取系统日志定位自身发生的异常，调用 logcat 命令时必须增加 -d 参数，即调用logcat不能阻塞进程一直等待；若应用未增加此参数，则系统会特殊处理，实现同等效果(增加参数-d)。如下格式：logcat -d 。

增加 -d 参数后，logcat 仅仅会读取当前系统缓存的日志，然后直接退出，不会一直阻塞住。未增加 -d 参数则会持续输出系统日志，对系统负载影响大，特别是系统日志量多的时候，对功耗的影响会非常的大。
来自vivo开发者文档
