### ISSUE TITLE
一加6t编译错误

### ISSUE THREAD

**Issue by Fyg369** [wxt1221/KernelSU#17]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

github-Action编译内核遇到如下图报错，在使用原作者ksu仓库可以顺利编译成功。
![Screenshot_20240114-085806](https://github.com/wxt1221/KernelSU/assets/142138034/f4da8301-ddc0-4b74-9d3d-f23f765ec2bf)

### Device info

- Device:
- OS Version:
- KernelSU Version:
- Kernel Version:

**Comment by Fyg369** [comment]
内核源码地址:https://github.com/Fyg369/mcd_kernel_oneplus_sdm845

**Comment by Fyg369** [comment]
![Screenshot_20240114-093807](https://github.com/wxt1221/KernelSU/assets/142138034/ac767958-ca1a-4a15-9bff-eacfd73f01ce)

**Comment by wxt1221** [comment]
请仔细阅读中文文档后进行编译。

**Comment by Fyg369** [comment]
> 请仔细阅读中文文档后进行编译。

不支持4.9是吗？

**Comment by wxt1221** [comment]
https://wxt1221.github.io/KernelSU/zh_CN/guide/how-to-integrate-for-non-gki.html

请仔细阅读本页面你可以找到答案

**Comment by Fyg369** [comment]
> https://wxt1221.github.io/KernelSU/zh_CN/guide/how-to-integrate-for-non-gki.html
> 
> 请仔细阅读本页面你可以找到答案

好的  感谢

**Comment by Fyg369** [comment]
按照文档教程操作出现如下图错误
![bug](https://github.com/wxt1221/KernelSU/assets/142138034/fe60c303-759c-4e65-b943-8b4f446d55c7)

**Comment by wxt1221** [comment]
https://github.com/wxt1221/KernelSU/commit/49c29b4c2d684f2b8ea41f77c6756a4f92124f54

**Comment by Fyg369** [comment]
> [49c29b4](https://github.com/wxt1221/KernelSU/commit/49c29b4c2d684f2b8ea41f77c6756a4f92124f54)

如下图报错
![微信图片_20240114182900](https://github.com/wxt1221/KernelSU/assets/142138034/9ebdb56a-929a-4f68-b39f-4483083cc851)

**Comment by Fyg369** [comment]
建议大佬在core_hook.c文件里加个判断may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义，如果内核源码存在这些定义就继续执行，如果不存在就跳过，保证内核源码在存在和不存在的情况下都不影响编译。

**Comment by wxt1221** [comment]
> 建议大佬在core_hook.c文件里加个判断may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义，如果内核源码存在这些定义就继续执行，如果不存在就跳过，保证内核源码在存在和不存在的情况下都不影响编译。

不好判断啊，你有什么想法吗，这些函数本来就是static定义的，怎么判？

**Comment by Fyg369** [comment]
> > 建议大佬在core_hook.c文件里加个判断may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义，如果内核源码存在这些定义就继续执行，如果不存在就跳过，保证内核源码在存在和不存在的情况下都不影响编译。
> 
> 不好判断啊，你有什么想法吗，这些函数本来就是static定义的，怎么判？

我也是菜鸟，我用的是6t官方氢系统安卓版本11，用的内核源码里没有may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义，不过我用原作者的ksu确实可以正常编译成功。

**Comment by Fyg369** [comment]
我尝试克隆大佬你的仓库后替换原作这core_hook.c文件确实可以编译成功，看来还是内核源码不存在may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义导致编译失败。
![微信图片_20240115135321](https://github.com/wxt1221/KernelSU/assets/142138034/c9a1db1e-51db-42a9-bcb2-5992952756ee)
![微信图片_20240115135425](https://github.com/wxt1221/KernelSU/assets/142138034/ea65c1d3-14b2-4abd-b0c1-f76ee05bff57)

**Comment by wxt1221** [comment]
是这样的，那几个函数是static定义，很难去从外部调用，只能把static定义去了，要不然就引一个函数到fs/namespace.c里面把函数地址搞出来，一样要改源码，而且如果这些函数被编译器裁掉了的话就更烦了，所以说就这样处理。

**Comment by wxt1221** [comment]
> > > 建议大佬在core_hook.c文件里加个判断may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义，如果内核源码存在这些定义就继续执行，如果不存在就跳过，保证内核源码在存在和不存在的情况下都不影响编译。
> > 
> > 
> > 不好判断啊，你有什么想法吗，这些函数本来就是static定义的，怎么判？
> 
> 我也是菜鸟，我用的是6t官方氢系统安卓版本11，用的内核源码里没有may_mount、check_mnt、mntput_no_expire 和 do_umount 函数的定义，不过我用原作者的ksu确实可以正常编译成功。

存在的，你搜一下就是了，只是static定义，你要把static去掉

**Comment by Fyg369** [comment]
> do_umount

有些不知所措   哈哈哈
![1](https://github.com/wxt1221/KernelSU/assets/142138034/0208e424-2961-41e1-b3ad-f96a88f5abdc)
![2](https://github.com/wxt1221/KernelSU/assets/142138034/48cf7e62-24a2-496e-8dbf-fdca1ef62abd)

**Comment by Fyg369** [comment]
> > 是这样的，那几个函数是static定义，很难去从外部调用，只能把static定义去了，要不然就引一个函数到fs/namespace.c里面把函数地址搞出来，一样要改源码，而且如果这些函数被编译器裁掉了的话就更烦了，所以说就这样处理。
> 
> 引一个函数到fs/namespace.c里面把函数地址搞出来是参考这里的吗？ ![3](https://private-user-images.githubusercontent.com/142138034/296675156-45aebdfb-9aa3-4662-b50a-17bdae706b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDI0NjksIm5iZiI6MTcwNTMwMjE2OSwicGF0aCI6Ii8xNDIxMzgwMzQvMjk2Njc1MTU2LTQ1YWViZGZiLTlhYTMtNDY2Mi1iNTBhLTE3YmRhZTcwNmIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNzAyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzQxMmIxYTlhMGM1YWZlZDA3YWRlYTgyYjkwMWVjMmYzNjUyMmU5OGRjNGE4NjZjOWIxOTdhNDM5NGI0NDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OiXD8puTaTSsj7XcKC-eTpUSoCzzf4lyHQgkGBD-m1Y)

根据这个教程操作删除static出现如下报错
![4](https://github.com/wxt1221/KernelSU/assets/142138034/58769e46-3bc3-4fab-9cc2-d6abc88ee85a)

**Comment by Fyg369** [comment]
感谢指导已经成功编译出来了，一开始用这个命令curl -LSs "https://raw.githubusercontent.com/wxt1221/KernelSU/main/kernel/setup.sh" | bash -克隆的稳定版缺少了#include "../../fs/mount.h"
后来用这个命令curl -LSs "https://raw.githubusercontent.com/wxt1221/KernelSU/main/kernel/setup.sh" | bash -s main克隆了开发版中有#include "../../fs/mount.h"就成功编译了
不过大佬这0.7.6版本管理器app似乎无法使用0.75没问题
![2](https://github.com/wxt1221/KernelSU/assets/142138034/6259deaa-af30-425e-bff1-0f5aad768be3)
![1](https://github.com/wxt1221/KernelSU/assets/142138034/a802bc65-f2bb-4650-9a0d-8270889e91c9)

**Comment by Fyg369** [comment]
好家伙我重新构建后，现在管理器无论0.7.5还是0.7.6都无法正常使用了，情况和上面第一张图一样，但是root和模块都正常就管理app不正常，不知道什么原因造成的。

**Comment by wxt1221** [comment]
下载Actions内最新管理器，因为签名大小问题重新更换了签名

**Comment by Fyg369** [comment]
> 下载Actions内最新管理器，因为签名大小问题重新更换了签名

没找到下载地方。。。。。

**Comment by wxt1221** [comment]
https://github.com/wxt1221/KernelSU/actions/runs/7509872942

**Comment by Fyg369** [comment]
> https://github.com/wxt1221/KernelSU/actions/runs/7509872942

感谢刚找到

**Comment by Fyg369** [comment]
麻烦再请教大佬个问题，就是删除static定义，构建出来的内核有什么影响吗？或者会不会导致系统安全问题？

**Comment by Fyg369** [comment]
> p影响没有，函数原来就在，static只改变编译出来的中间产物，使其无法通过其他文件extern定义，函数本身行为不改变。

好的 非常感谢您的帮助

**Comment by Fyg369** [comment]
话说这APatch里的KP模块有什么优势吗？
![Screenshot_20240116-135643](https://github.com/wxt1221/KernelSU/assets/142138034/36d6fb94-03d8-407d-8229-c68265aa9805)
![Screenshot_20240116-135709](https://github.com/wxt1221/KernelSU/assets/142138034/7fca6386-dcfb-4d18-b870-63501bf6d8e6)
![Screenshot_20240116-135627](https://github.com/wxt1221/KernelSU/assets/142138034/ecb5a263-4e52-42cb-a2c9-b104ad8d50c3)
![Screenshot_20240116-135635](https://github.com/wxt1221/KernelSU/assets/142138034/5e536a2d-efd7-4350-a107-249902777bad)
![Screenshot_20240116-135652](https://github.com/wxt1221/KernelSU/assets/142138034/22903afb-02a6-4fd5-b00e-ce69a1423942)

**Comment by wxt1221** [comment]
我不知道（

**Comment by wxt1221** [comment]
应该没区别

**Comment by Fyg369** [comment]
更新了内核管理器又挂了，签名又出了问题？
![Screenshot_20240129-014709](https://github.com/Bot-wxt1221/KernelSU/assets/142138034/5e5f5332-1a85-4787-8b34-40a469c15f90)

**Comment by Fyg369** [comment]
原来大佬改了setup.sh里的链接代码，不过最新的管理器还是一样的问题，不知道是否签名大小问题。
