### ISSUE TITLE
App signatures changed

### ISSUE THREAD

**Issue by y0geshx** [wxt1221/KernelSU#4]
### Describe your problem.

App signatures changed

**Comment by wxt1221** [comment]
完了搞忘了，去下最新CI吧

**Comment by wxt1221** [comment]
It wiil be rebuilt a little latter

**Comment by wxt1221** [comment]
好像完全是挂的，等我修一下

**Comment by wxt1221** [comment]
Solved by 0.7.6. It is now building.
